package com.csye6225.spring2019.courseservice.DataModel;
import java.util.Date;

//import javax.xml.bind.annotation.XmlRootElement;

//@XmlRootElement



import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="professor")
public class Professor {
private String id;
private String firstName;
private String department;
private long professorId;
private String joiningDate;

public Professor() {
	
}

public Professor(String id,long professorId, String firstName, String department, String joiningDate) {
	this.setId(id);
	this.professorId = professorId;
	this.firstName = firstName;
	this.department = department;
	this.joiningDate = joiningDate;
}


@DynamoDBAttribute(attributeName="firstName")
public String getFirstName() {
	return firstName;
}
public void setFirstName(String firstName) {
	this.firstName = firstName;
}

@DynamoDBAttribute(attributeName="department")
public String getDepartment() {
	return department;
}
public void setDepartment(String department) {
	this.department = department;
}

@DynamoDBIndexHashKey(attributeName = "professorId",globalSecondaryIndexName = "professor-index")
public long getProfessorId() {
	return professorId;
}
public void setProfessorId(long professorId) {
	this.professorId = professorId;
}

@DynamoDBAttribute(attributeName="joiningDate")
public String getJoiningDate() {
	return joiningDate;
}
public void setJoiningDate(String joiningDate) {
	this.joiningDate = joiningDate;
}

@DynamoDBIgnore
@Override
public String toString() { 
	return "ProfId=" + getProfessorId() + ", firstName=" + getFirstName()
			+ ", department=" + getDepartment() + ", joiningDate=" + getJoiningDate();
}
@DynamoDBHashKey(attributeName = "id")
@DynamoDBAutoGeneratedKey
public String getId() {
	return id;
}

public void setId(String id) {
	this.id = id;
}

}